# Importance of Feature selection:
Feature selection is the process of choosing only the most useful input features for a machine learning model. It helps improve model performance, reduces noise and makes results easier to understand.

1.Helps remove irrelevant and redundant features
2.Improves accuracy and reduces overfitting
3.Speeds up model training
4.Makes models simpler and easier to interpret

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
dataset1=pd.read_csv("Heart_Dataset.csv.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2, dtype=int, drop_first=0 or 1)

In [3]:
df2

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [4]:
df2["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [5]:
indep=df2[["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal",]]
dep=df2[["target"]]

In [6]:
indep

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [7]:
dep

     target
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep,dep, test_size = 0.30,random_state = 0)

#Decision Tree Classifier:

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [10]:
y_pred=classifier.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [12]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [13]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.80      0.75      0.78        44
           1       0.78      0.83      0.80        47

    accuracy                           0.79        91
   macro avg       0.79      0.79      0.79        91
weighted avg       0.79      0.79      0.79        91

# Random ForestClassifier

In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy', random_state=0)
classifier.fit(X_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [26]:
y_pred=classifier.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [28]:
print(cm)

[[30 14]
 [11 36]]

In [29]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [30]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.73      0.68      0.71        44
           1       0.72      0.77      0.74        47

    accuracy                           0.73        91
   macro avg       0.73      0.72      0.72        91
weighted avg       0.73      0.73      0.72        91

In [31]:
from sklearn.svm import SVC
classifier=SVC(kernel="rbf", random_state=0)
classifier.fit(X_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(random_state=0)

In [32]:
y_pred=classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [34]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.73      0.68      0.71        44
           1       0.72      0.77      0.74        47

    accuracy                           0.73        91
   macro avg       0.73      0.72      0.72        91
weighted avg       0.73      0.73      0.72        91

In [35]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.82      0.64      0.72        44
           1       0.72      0.87      0.79        47

    accuracy                           0.76        91
   macro avg       0.77      0.75      0.75        91
weighted avg       0.77      0.76      0.75        91

[[28 16]
 [ 6 41]]

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

#Report :
Compare with all alogorithms Decision tree is the best one  becaz the accuracy value is 79